export const STATS = [
    { name: 'AGE', value: 'age'},
    { name: 'HEIGHT', value: 'height'},
    { name: 'WEIGHT', value: 'weight'},
    // { name: 'BADGES', value: 'weight'},
    { name: 'OVR', value: 'overall' },
    { name: 'OUT', value: 'outside' },
    { name: 'OMID', value: 'openMid' },
    { name: 'CNMID', value: 'contestedMid' },
    { name: 'MVMID', value: 'movingMid' },
    { name: '3PT', value: 'open3PT' },
    { name: 'CN3PT', value: 'contested3PT' },
    { name: 'MV3PT', value: 'moving3PT' },
    { name: 'SHTIQ', value: 'shotIQ' },
    { name: 'FT', value: 'freeThrow' },
    { name: 'OFFCONS', value: 'offensiveConsistency' },
    { name: 'SPD', value: 'speed' },
    { name: 'ACC', value: 'acceleration' },
    { name: 'VERT', value: 'vertical' },
    { name: 'STR', value: 'strength' },
    { name: 'STA', value: 'stamina' },
    { name: 'HUS', value: 'hustle' },
    { name: 'DUR', value: 'durability' },
    { name: 'CLS', value: 'shotClose' },
    { name: 'STNLAY', value: 'standingLayup' },
    { name: 'DRILAY', value: 'drivingLayup' },
    { name: 'STNDNK', value: 'standingDunk' },
    { name: 'DRIDUNK', value: 'drivingDunk' },
    { name: 'CNTDUNK', value: 'contactDunk' },
    { name: 'DFOUL', value: 'drawFoul' },
    { name: 'POST', value: 'postControl' },
    { name: 'HOOK', value: 'postHook' },
    { name: 'FADE', value: 'postFade' },
    { name: 'HAND', value: 'hands' },
    { name: 'BALLCTR', value: 'ballControl' },
    { name: 'PASSACC', value: 'passingAccuracy' },
    { name: 'PASSVIS', value: 'passingVision' },
    { name: 'PASSIQ', value: 'passingIQ' },
    { name: 'SPDBALL', value: 'speedBall' },
    { name: 'ONBALLDEF', value: 'onBallDefIQ' },
    { name: 'POSTDEFIQ', value: 'postDefIQ' },
    { name: 'PNRDEFIQ', value: 'standingDunk' },
    { name: 'HELP', value: 'standingDunk' },
    { name: 'LATQUICK', value: 'standingDunk' },
    { name: 'PASSPRC', value: 'standingDunk' },
    { name: 'REACT', value: 'standingDunk' },
    { name: 'STEAL', value: 'standingDunk' },
    { name: 'BLK', value: 'standingDunk' },
    { name: 'CONTST', value: 'standingDunk' },
    { name: 'DEFCONS', value: 'standingDunk' },
    { name: 'OFFREB', value: 'standingDunk' },
    { name: 'DEFREB', value: 'standingDunk' },
    { name: 'BOXOUT', value: 'standingDunk' }
  ];
