export const STATS = [
  { header: 'OMID', name: 'Open shot mid', value: 'openMid', selected: false },
  { header: 'CNMID', name: 'Contested shot mid', value: 'contestedMid', selected: false },
  { header: 'MVMID', name: 'Moving shot mid', value: 'movingMid', selected: false },
  { header: '3PT', name: 'Open shot 3PT', value: 'open3PT', selected: false },
  { header: 'CN3PT', name: 'Contested shot 3PT', value: 'contested3PT', selected: false },
  { header: 'MV3PT', name: 'Moving shot 3PT', value: 'moving3PT', selected: false },
  { header: 'SHTIQ', name: 'Shot IQ', value: 'shotIQ', selected: false },
  { header: 'FT', name: 'Free Throw', value: 'freeThrow', selected: false },
  { header: 'OFFCONS', name: 'Offensive Consistency', value: 'offensiveConsistency', selected: false },
  { header: 'SPD', name: 'Speed', value: 'speed', selected: false },
  { header: 'ACC', name: 'Acceleration', value: 'acceleration', selected: false },
  { header: 'VERT', name: 'Vertical', value: 'vertical', selected: false },
  { header: 'STR', name: 'Strength', value: 'strength', selected: false },
  { header: 'STA', name: 'Stamina', value: 'stamina', selected: false },
  { header: 'HUS', name: 'Hustle', value: 'hustle', selected: false },
  { header: 'DUR', name: 'Durability', value: 'durability', selected: false },
  { header: 'CLS', name: 'Shot Close', value: 'shotClose', selected: false },
  { header: 'STNLAY', name: 'Standing Layup', value: 'standingLayup', selected: false },
  { header: 'DRILAY', name: 'Driving Layup', value: 'drivingLayup', selected: false },
  { header: 'STNDNK', name: 'Standing Dunk', value: 'standingDunk', selected: false },
  { header: 'DRIDUNK', name: 'Driving Layup', value: 'drivingDunk', selected: false },
  { header: 'CNTDUNK', name: 'Contact Dunk', value: 'contactDunk', selected: false },
  { header: 'DFOUL', name: 'Draw Foul', value: 'drawFoul', selected: false },
  { header: 'POST', name: 'Post Control', value: 'postControl', selected: false },
  { header: 'HOOK', name: 'Post Hook', value: 'postHook', selected: false },
  { header: 'FADE', name: 'Post fadeaway', value: 'postFade', selected: false },
  { header: 'HAND', name: 'Hands', value: 'hands', selected: false },
  { header: 'BALLCTR', name: 'Ball Control', value: 'ballControl', selected: false },
  { header: 'PASSACC', name: 'Passing Accuracy', value: 'passingAccuracy', selected: false },
  { header: 'PASSVIS', name: 'Passing Vision', value: 'passingVision', selected: false },
  { header: 'PASSIQ', name: 'Passing IQ', value: 'passingIQ', selected: false },
  { header: 'SPDBALL', name: 'Speed with Ball', value: 'speedBall', selected: false },
  { header: 'ONBALLDEF', name: 'On Ball Defensive IQ', value: 'onBallDefIQ', selected: false },
  { header: 'POSTDEFIQ', name: 'Post Defensive IQ', value: 'lowPostDefIQ', selected: false },
  { header: 'PNRDEFIQ', name: 'Standing Dunk', value: 'pickNRollDefIQ', selected: false },
  { header: 'HELP', name: 'Help defense', value: 'helpDefIQ', selected: false },
  { header: 'LATQUICK', name: 'Lateral Quickness', value: 'lateralQuickness', selected: false },
  { header: 'PASSPRC', name: 'Pass perception', value: 'passPerception', selected: false },
  { header: 'REACT', name: 'Reaction Time', value: 'reactionTime', selected: false },
  { header: 'STEAL', name: 'Steal', value: 'steal', selected: false },
  { header: 'BLK', name: 'Block', value: 'block', selected: false },
  { header: 'CONTST', name: 'Shot Contest', value: 'shotContest', selected: false },
  { header: 'DEFCONS', name: 'Defensive Consistency', value: 'defConsistency', selected: false },
  { header: 'OFFREB', name: 'Offensive Rebound', value: 'offRebound', selected: false },
  { header: 'DEFREB', name: 'Defensive Rebound', value: 'defRebound', selected: false },
  { header: 'BOXOUT', name: 'Boxout', value: 'boxout', selected: false }
];

export const TIERS = [
  { name: 'Bronze', value: 'bronze' },
  { name: 'Silver', value: 'silver' },
  { name: 'Gold', value: 'gold' },
  { name: 'Sapphire', value: 'sapphire' },
  { name: 'Ruby', value: 'ruby' },
  { name: 'Heat Check', value: 'heatcheck' },
  { name: 'Amethyst', value: 'amethyst' },
  { name: 'Onyx', value: 'onyx' },
  { name: 'Diamond', value: 'diamond' },
  { name: 'Pink Diamond', value: 'pinkdiamond' },
  { name: 'Galaxy Opal', value: 'galaxyopal' }
];
